import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterProvider from "@/components/ToasterProvider/ToasterProvider";
import Providers from "@/lib/SessionProvider";
// import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/LandingPage/Header";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Track Smart 2.0 App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={cn(font.className, " bg-white/60 dark:bg-[#081632]")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableColorScheme={false}
            storageKey="discord-theme"
          >
            <Header />
            <main className="container">
              <div className="flex items-start justify-center min-h-screen">
                <div>
                  <ToasterProvider />
                  {children}
                </div>
              </div>
            </main>
          </ThemeProvider>
        </body>
      </html>
    </Providers>
  );
}
